### ISSUE TITLE
bug with multi datepicker on hijri formate

### ISSUE THREAD

**Issue by mohamedKamalEG** [balbarak/bootstrap-hijri-datepicker#13]
When I add  class "hijri-date-input" to 2 input for example:
$(".hijri-date-input").hijriDatePicker();

It works only for the first input. and return console error:
<img width="1317" alt="sc" src="https://user-images.githubusercontent.com/12998225/74312058-ee28e980-4d81-11ea-9dc8-deac8168cd31.png">

**Comment by balbarak** [comment]
confirmed, thank you

a new release will ship soon to fix some issues

**Comment by mohamedKamalEG** [comment]
okay, thank you.
also, I hope to support the date range, so when I set one input date "from" & another input date "to".
like this attached photo:
<img width="425" alt="Screen Shot 2020-02-13 at 4 34 03 PM" src="https://user-images.githubusercontent.com/12998225/74440262-bd7aaa00-4e7e-11ea-829e-512f1bfea4e1.png">

**Comment by balbarak** [comment]
issue has been resolved in release v1.0.0

Thanks
