### ISSUE TITLE
Uncaught TypeError: n.iYear is not a function

### ISSUE THREAD

**Issue by nohaGazzaz** [balbarak/bootstrap-hijri-datepicker#2]
when following the steps mentioned in the readme file i get this error

`
Uncaught TypeError: n.iYear is not a function
`

in the console

**Comment by balbarak** [comment]
make sure you include the files in `dist` folder 

* `bootstrap-datetimepicker.min.css`
* `bootstrap-hijri-datepicker.min.js`

and include momentjs and jquery with the specific version or above from cdn or any other files if you have it in your disk
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>
```

**Comment by programmeranamul** [comment]
![image](https://user-images.githubusercontent.com/76878888/187337488-b01ed784-712c-440d-b3e3-527c6bd9c1ff.png)
![image](https://user-images.githubusercontent.com/76878888/187337544-81c4c3dd-f444-4cb4-be22-da02fcd5f513.png)

I am working on a sveltekit project. When I am trying to import moment-hijri, it's say me "moment.localeData is not a function". But It's work fine in my sapper project. How can I solve this?
