### ISSUE TITLE
Unable to Choose Hijri Dates Earlier Than 1355 Hijri year

### ISSUE THREAD

**Issue by zeejay95** [balbarak/bootstrap-hijri-datepicker#46]
Bootstrap Hijri Datepicker was working fine, but now we have a requirement to select Hijri dates earlier than the year 1355, and the datepicker seems to restrict this, and it get stuck there.

I've tried several approaches to resolve this problem, but haven't had any success so far. Has anyone else encountered a similar issue? If you have, could you please share any insights or solutions you've found?

**Comment by balbarak** [comment]
Hello, 

this is intend because dates before 1355 is not calculated correctly

**Comment by zeejay95** [comment]
Dear I have resolved this issue.

This restriction was from moment-hijri. 
And I have modified moment-hijri and its working fine.

**Comment by Mo7mud** [comment]
> Dear I have resolved this issue.
> 
> This restriction was from moment-hijri. And I have modified moment-hijri and its working fine.

Can you please share your modifications.
Thank you
