### ISSUE TITLE
On change event

### ISSUE THREAD

**Issue by Umarali33** [balbarak/bootstrap-hijri-datepicker#6]
How can I pick on change event? I try lots of methods but nothing worked.
`
jQuery("#CaseHijriDate)").hijriDatePicker({
                locale: "ar-sa",
                format: 'mm/dd/yyyy',
                hijri: true,
                hijriFormat: 'iMM/iDD/iYYYY',
                showSwitcher: false,
                allowInputToggle: false,
                showTodayButton: true,
                useCurrent: true,
                isRTL: false,
                keepOpen: false,
                showClear: true,
                showClose: false
             }).change(function () {
                 alert('test');
             });
`
i also try below code but not succes
`
 jQuery('#CaseHijriDate)').change(function () {
                alert('test');
            });
`
also please mention all events which is working.

**Comment by balbarak** [comment]
in order to catch change event use the followings

```js

$("#CaseHijriDate").on('dp.change', function (event) {
            console.log(event.date)
});
```

other events
* `dp.hide` on hide
* `dp.show` on show
* `dp.error` on error
* `dp.update` on update

we should add this in the documentations

Thanks

**Comment by Umarali33** [comment]
Thanks it's worked.

**Comment by Nadirdasti** [comment]
$("#CaseHijriDate").on('dp.change', function (event) {
            console.log(event.date)
});
its return georgian date.i want selected date should be in hijri format.

**Comment by balbarak** [comment]
You can try

`$(this).data('date');`

Thanks
